<?php

use Illuminate\Database\Seeder;
use Symfony\Component\Console\Output\ConsoleOutput;

class EventsTableSeeder extends Seeder {

	public function run()
	{
        /**
         * Note: Convert CSV files generated by Excel to UTF-8
         */

        $output = new ConsoleOutput();

		$events = file('resources/data/events/events.txt');

		foreach($events as $event) {
            try {
                list($name, $slug, $location, $start_date, $end_date, $visible, $organizer_id, $region_id, $profile, $meta_description) = explode(';', trim($event));

                $data[] = [
                    'user_id'			=> 0,
                    'name'				=> $name,
                    'location'			=> $location,
                    'slug'				=> $slug,
                    'start_date'		=> Date::germanToSql($start_date),
                    'end_date'			=> Date::germanToSql($end_date),
                    'visible'			=> $visible,
                    'organizer_id'		=> $organizer_id,
                    'region_id'			=> $region_id,
                    'profile'			=> $profile,
                    'meta_description'	=> $meta_description,
                    'created_at'		=> new DateTime,
                    'updated_at'		=> new DateTime
                ];
            } catch(\Exception $e) {
                $output->writeln('Operation aborted.');
                $output->writeln('Problem parsing this line: ' . Str::limit($event, 50));
                exit;
            }
		}

        if(isset($data)) {
            DB::table('events')->insert($data);
            $output->writeln(count($data) . ' events imported.');
        }
	}
}