<?php

use Illuminate\Database\Seeder;
use Symfony\Component\Console\Output\ConsoleOutput;

class OrganizersTableSeeder extends Seeder {

	public function run()
	{
        /**
         * Note: Convert CSV files generated by Excel to UTF-8
         */

        $output = new ConsoleOutput();
        
		$organizers = file('resources/data/organizers.txt');

		foreach($organizers as $organizer) {
            try {
                list($name, $slug, $website, $featured, $meta_description, $profile) = explode(';', trim($organizer));

                $data[] = [
                    'name'				=> $name,
                    'slug'				=> $slug,
                    'website'			=> $website,
                    'featured'			=> $featured,
                    'meta_description'	=> $meta_description,
                    'profile' 			=> $profile,
                    'created_at'		=> new DateTime,
                    'updated_at'		=> new DateTime
                ];

            } catch(\Exception $e) {
                $output->writeln('Operation aborted.');
                $output->writeln('Problem parsing this line: ' . Str::limit($organizer, 50));
                exit;
            }
        }

        if(isset($data)) {
            DB::table('organizers')->insert($data);
            $output->writeln(count($data) . ' organizers imported.');
		}
	}
}